C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pyinitGEOPACK2(setupfunc)
      external setupfunc
      real G(105)
      real H(105)
      real REC(105)
      common /GEOPACK2/ G,H,REC
      call setupfunc(G,H,REC)
      end

      subroutine f2pyinitGEOPACK1(setupfunc)
      external setupfunc
      real AA(10)
      real SPS
      real CPS
      real BB(22)
      common /GEOPACK1/ AA,SPS,CPS,BB
      call setupfunc(AA,SPS,CPS,BB)
      end


